### PR TITLE
fix: base64 - rm line breaks

### PR DESCRIPTION
**Pull request by mvayngrib**
some data uri parsers have trouble with these line breaks

### CODE REVIEW

**Comment by mvayngrib** [comment]
@DoDoENT done

**Comment by mvayngrib** [comment]
@DoDoENT rebased again

**Comment by DoDoENT** [comment]
@juraskrlec, @jcular, can you guys review that and possibly add those changes to our internal plugin generator system, so that next release will not overwrite those changes?

**Comment by jcular** [comment]
Hey @mvayngrib, you missed one The one in [MBPaymentCardCombinedRecognizerWrapper](    [jsonResult setValue:[self.result.digitalSignature base64EncodedStringWithOptions:NSDataBase64EncodingEndLineWithLineFeed] forKey:@"digitalSignature"];). 
Will you update your pr, or I can merge it and change that one myself?

**Comment by mvayngrib** [comment]
@jcular oops, fixed!

**Comment by jcular** [comment]
@mvayngrib awesome thx

**Pull request merged**
