### PR TITLE
feat: nzdl (ios)

### PR DESCRIPTION
**Pull request by mvayngrib**
this is on top of the #44 PR, so better review that one first :)

some unresolved issues:
- address is not extracted, I get a blank string
- cropped image seems to be basically the same as the signature image. I expected it to be the full id card area

Edit: updated unresolved issues. Got date of birth, date of issue/expiry, though the latter two are not present on the front most licenses.

### CODE REVIEW

**Comment by mvayngrib** [comment]
some more testing. When requesting ALL images for nzdl I get:

successful:
image

signature:
image

cropped (same as sig for some reason):
image

face:
image

When requesting just face and cropped I get:

face (with a bigger size than above):
image

cropped (same as face for some reason):
image

**Comment by cularj** [comment]
@mvayngrib 
I'll test this out and try to see what is the issue

**Comment by mvayngrib** [comment]
@cularj cool, thanks for checking that. Will it be possible in the near future to get both the cropped image and the face?

**Comment by cularj** [comment]
@mvayngrib Yes.

**Comment by cularj** [comment]
Hi @mvayngrib 

We just updated the plugin and fixed this issue with image extraction.
Unfortunately, this also means we had to make some breaking API changes. We've also added NZDL but without signature image extraction. Now every recognizer result contains the face image and document(previously named cropped) image if you requested it and of course if it can provide them. This change also allows you to add signature image extraction that won't clash with the extraction of other images. 

Kind regards,
Jure

**Pull request closed without merging**
